// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TnbIcoms.Infrastructure.Persistence;

#nullable disable

namespace TnbIcoms.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819121716_RestructureProjectFields")]
    partial class RestructureProjectFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Audit.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLogs", "audit");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Audit.SavedReportFilter", b =>
                {
                    b.Property<int>("SavedReportFilterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SavedReportFilterId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilterJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilterName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("ReportCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SavedReportFilterId");

                    b.ToTable("SavedReportFilters", "audit");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Auth.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", "auth");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Auth.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolePermissionId"));

                    b.Property<bool>("IsGranted")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions", "auth");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Auth.RoleTransferRequest", b =>
                {
                    b.Property<int>("RoleTransferRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleTransferRequestId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<int>("FromRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ToRoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleTransferRequestId");

                    b.HasIndex("FromRoleId");

                    b.HasIndex("ToRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleTransferRequests", "auth");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Auth.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AspNetUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("AuthType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("GcuTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("TnbId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Users", "auth");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Auth.UserGcuStation", b =>
                {
                    b.Property<int>("UserGcuStationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserGcuStationId"));

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserGcuStationId");

                    b.HasIndex("StationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGcuStations", "auth");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.AuthorisationPersonnel", b =>
                {
                    b.Property<int>("AuthorisationPersonnelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorisationPersonnelId"));

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StaffId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("AuthorisationPersonnelId");

                    b.HasIndex("ZoneId");

                    b.ToTable("AuthorisationPersonnel", "config");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.ConflictingLine", b =>
                {
                    b.Property<int>("ConflictingLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConflictingLineId"));

                    b.Property<int>("ConflictingEquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConflictingLineId");

                    b.HasIndex("ConflictingEquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("ConflictingLines", "config");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.DropdownValue", b =>
                {
                    b.Property<int>("DropdownValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DropdownValueId"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("ValueCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ValueLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DropdownValueId");

                    b.HasIndex("CategoryCode", "ValueCode")
                        .IsUnique();

                    b.ToTable("DropdownValues", "config");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<string>("EquipmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOffPoint")
                        .HasColumnType("bit");

                    b.Property<string>("LineFilterType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MvaRatingId")
                        .HasColumnType("int");

                    b.Property<string>("OffPointRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<int>("VoltageLevelId")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("EquipmentId");

                    b.HasIndex("EquipmentCode")
                        .IsUnique();

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("StationId");

                    b.HasIndex("VoltageLevelId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Equipment", "config");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.EquipmentType", b =>
                {
                    b.Property<int>("EquipmentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentTypeId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VoltageLevelId")
                        .HasColumnType("int");

                    b.HasKey("EquipmentTypeId");

                    b.HasIndex("VoltageLevelId", "TypeName")
                        .IsUnique();

                    b.ToTable("EquipmentTypes", "config");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.Organisation", b =>
                {
                    b.Property<int>("OrganisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganisationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGcu")
                        .HasColumnType("bit");

                    b.Property<string>("OrganisationCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OrganisationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("OrganisationId");

                    b.HasIndex("OrganisationCode")
                        .IsUnique();

                    b.HasIndex("OrganisationName")
                        .IsUnique();

                    b.HasIndex("ZoneId");

                    b.ToTable("Organisations", "config");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.OutageTypeRule", b =>
                {
                    b.Property<int>("OutageTypeRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OutageTypeRuleId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxLeadDays")
                        .HasColumnType("int");

                    b.Property<int?>("MinLeadDays")
                        .HasColumnType("int");

                    b.Property<string>("OutageTypeCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("OutageTypeRuleId");

                    b.ToTable("OutageTypeRules", "config");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(210)
                        .HasColumnType("nvarchar(210)");

                    b.Property<string>("ProjectSuffix")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TpCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.HasIndex("TpCode")
                        .IsUnique();

                    b.HasIndex("ZoneId");

                    b.ToTable("Projects", "config");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StationId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OrgId")
                        .HasColumnType("int");

                    b.Property<string>("SldFileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationAbbr")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("StationId");

                    b.HasIndex("OrgId");

                    b.HasIndex("StationAbbr")
                        .IsUnique();

                    b.HasIndex("StationName")
                        .IsUnique();

                    b.HasIndex("ZoneId");

                    b.ToTable("Stations", "config");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.VoltageLevel", b =>
                {
                    b.Property<int>("VoltageLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoltageLevelId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("VoltageLevelId");

                    b.HasIndex("LevelName")
                        .IsUnique();

                    b.ToTable("VoltageLevels", "config");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.Zone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ZoneAbbr")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ZoneName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ZoneId");

                    b.ToTable("Zones", "config");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.ZoneLocation", b =>
                {
                    b.Property<int>("ZoneLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneLocationId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("ZoneLocationId");

                    b.HasIndex("ZoneId");

                    b.ToTable("ZoneLocations", "config");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Handover.HandoverEntry", b =>
                {
                    b.Property<int>("HandoverEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HandoverEntryId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<int?>("RelatedOutageId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.HasKey("HandoverEntryId");

                    b.HasIndex("ShiftId");

                    b.ToTable("HandoverEntries", "handover");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Handover.HandoverShift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<int?>("ControlAssistantId")
                        .HasColumnType("int");

                    b.Property<int?>("ControlManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DespatcherId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PassedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PassedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SwitchEngineer1Id")
                        .HasColumnType("int");

                    b.Property<int?>("SwitchEngineer2Id")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("ShiftId");

                    b.HasIndex("ZoneId");

                    b.ToTable("HandoverShifts", "handover");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.Authorisation", b =>
                {
                    b.Property<int>("AuthorisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorisationId"));

                    b.Property<string>("AuthorisationNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("OutageId")
                        .HasColumnType("int");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TakenActiveAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TakenCompletedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AuthorisationId");

                    b.HasIndex("OutageId");

                    b.ToTable("Authorisations", "dbo");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.ChangeRequest", b =>
                {
                    b.Property<int>("ChangeRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChangeRequestId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OutageId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ChangeRequestId");

                    b.HasIndex("OutageId");

                    b.ToTable("ChangeRequests", "dbo");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.CommissioningMemo", b =>
                {
                    b.Property<int>("CommissioningMemoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommissioningMemoId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("MemoNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OutageId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CommissioningMemoId");

                    b.HasIndex("OutageId");

                    b.ToTable("CommissioningMemos", "dbo");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.GcuAcknowledgement", b =>
                {
                    b.Property<int>("GcuAcknowledgementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GcuAcknowledgementId"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GcuUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAutoAgreed")
                        .HasColumnType("bit");

                    b.Property<int>("OutageId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GcuAcknowledgementId");

                    b.HasIndex("OutageId");

                    b.ToTable("GcuAcknowledgements", "dbo");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.Outage", b =>
                {
                    b.Property<int>("OutageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OutageId"));

                    b.Property<DateTime?>("ActualEndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<string>("ContingencyPlanUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DsoAgreedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DsoAgreedBySystem")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ExtendedEndAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GncStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GnmStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HasPtw")
                        .HasColumnType("bit");

                    b.Property<string>("Highlights")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGcuNotified")
                        .HasColumnType("bit");

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Justification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineFilterType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NotTakenReasonId")
                        .HasColumnType("int");

                    b.Property<string>("OutageClass")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OutageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("OutageNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OutageTypeCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("PlannedEndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlannedStartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlannerStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrimaryEquipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestorStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RestorationId")
                        .HasColumnType("int");

                    b.Property<int?>("SequenceId")
                        .HasColumnType("int");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("UnderStudyNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("VoltageLevelId")
                        .HasColumnType("int");

                    b.Property<string>("WorkTypeCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("OutageId");

                    b.HasIndex("PrimaryEquipmentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StationId");

                    b.HasIndex("VoltageLevelId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Outages", "dbo");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.OutageAdditionalEquipment", b =>
                {
                    b.Property<int>("OutageAdditionalEquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OutageAdditionalEquipmentId"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("OutageId")
                        .HasColumnType("int");

                    b.HasKey("OutageAdditionalEquipmentId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("OutageId");

                    b.ToTable("OutageAdditionalEquipment", "dbo");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.OutageNotifyEmail", b =>
                {
                    b.Property<int>("OutageNotifyEmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OutageNotifyEmailId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OutageId")
                        .HasColumnType("int");

                    b.HasKey("OutageNotifyEmailId");

                    b.HasIndex("OutageId");

                    b.ToTable("OutageNotifyEmails", "dbo");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.OutageOffPoint", b =>
                {
                    b.Property<int>("OutageOffPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OutageOffPointId"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("OutageId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OutageOffPointId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("OutageId");

                    b.ToTable("OutageOffPoints", "dbo");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.OutagePic", b =>
                {
                    b.Property<int>("OutagePicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OutagePicId"));

                    b.Property<int>("OutageId")
                        .HasColumnType("int");

                    b.Property<string>("PicContact")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PicName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PicRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OutagePicId");

                    b.HasIndex("OutageId");

                    b.ToTable("OutagePics", "dbo");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.SingleLineDiagram", b =>
                {
                    b.Property<int>("SingleLineDiagramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SingleLineDiagramId"));

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OutageId")
                        .HasColumnType("int");

                    b.Property<int>("RevisionNo")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("SingleLineDiagramId");

                    b.HasIndex("OutageId");

                    b.ToTable("SingleLineDiagrams", "dbo");
                });

            modelBuilder.Entity("TnbIcoms.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TnbId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TnbIcoms.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TnbIcoms.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TnbIcoms.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TnbIcoms.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Auth.RolePermission", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Auth.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Auth.RoleTransferRequest", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Auth.Role", "FromRole")
                        .WithMany()
                        .HasForeignKey("FromRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TnbIcoms.Domain.Entities.Auth.Role", "ToRole")
                        .WithMany()
                        .HasForeignKey("ToRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TnbIcoms.Domain.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromRole");

                    b.Navigation("ToRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Auth.User", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Config.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TnbIcoms.Domain.Entities.Auth.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TnbIcoms.Domain.Entities.Config.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("Role");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Auth.UserGcuStation", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Config.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TnbIcoms.Domain.Entities.Auth.User", "User")
                        .WithMany("GcuStations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.AuthorisationPersonnel", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Config.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.ConflictingLine", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Config.Equipment", "ConflictingEquipment")
                        .WithMany()
                        .HasForeignKey("ConflictingEquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TnbIcoms.Domain.Entities.Config.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConflictingEquipment");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.Equipment", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Config.EquipmentType", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TnbIcoms.Domain.Entities.Config.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TnbIcoms.Domain.Entities.Config.VoltageLevel", "VoltageLevel")
                        .WithMany()
                        .HasForeignKey("VoltageLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TnbIcoms.Domain.Entities.Config.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipmentType");

                    b.Navigation("Station");

                    b.Navigation("VoltageLevel");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.EquipmentType", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Config.VoltageLevel", "VoltageLevel")
                        .WithMany()
                        .HasForeignKey("VoltageLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VoltageLevel");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.Organisation", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Config.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.Project", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Config.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.Station", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Config.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TnbIcoms.Domain.Entities.Config.Zone", "Zone")
                        .WithMany("Stations")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.ZoneLocation", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Config.Zone", "Zone")
                        .WithMany("Locations")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Handover.HandoverEntry", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Handover.HandoverShift", "Shift")
                        .WithMany("Entries")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Handover.HandoverShift", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Config.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.Authorisation", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Outage.Outage", "Outage")
                        .WithMany("Authorisations")
                        .HasForeignKey("OutageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Outage");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.ChangeRequest", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Outage.Outage", "Outage")
                        .WithMany("ChangeRequests")
                        .HasForeignKey("OutageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Outage");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.CommissioningMemo", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Outage.Outage", "Outage")
                        .WithMany("CommissioningMemos")
                        .HasForeignKey("OutageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Outage");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.GcuAcknowledgement", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Outage.Outage", "Outage")
                        .WithMany("GcuAcknowledgements")
                        .HasForeignKey("OutageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outage");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.Outage", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Config.Equipment", "PrimaryEquipment")
                        .WithMany()
                        .HasForeignKey("PrimaryEquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TnbIcoms.Domain.Entities.Config.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TnbIcoms.Domain.Entities.Config.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TnbIcoms.Domain.Entities.Config.VoltageLevel", "VoltageLevel")
                        .WithMany()
                        .HasForeignKey("VoltageLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TnbIcoms.Domain.Entities.Config.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PrimaryEquipment");

                    b.Navigation("Project");

                    b.Navigation("Station");

                    b.Navigation("VoltageLevel");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.OutageAdditionalEquipment", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Config.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TnbIcoms.Domain.Entities.Outage.Outage", "Outage")
                        .WithMany("AdditionalEquipment")
                        .HasForeignKey("OutageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Outage");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.OutageNotifyEmail", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Outage.Outage", "Outage")
                        .WithMany("NotifyEmails")
                        .HasForeignKey("OutageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outage");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.OutageOffPoint", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Config.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TnbIcoms.Domain.Entities.Outage.Outage", "Outage")
                        .WithMany("OffPoints")
                        .HasForeignKey("OutageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Outage");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.OutagePic", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Outage.Outage", "Outage")
                        .WithMany("Pics")
                        .HasForeignKey("OutageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outage");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.SingleLineDiagram", b =>
                {
                    b.HasOne("TnbIcoms.Domain.Entities.Outage.Outage", "Outage")
                        .WithMany("SingleLineDiagrams")
                        .HasForeignKey("OutageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Outage");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Auth.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Auth.User", b =>
                {
                    b.Navigation("GcuStations");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Config.Zone", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Handover.HandoverShift", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("TnbIcoms.Domain.Entities.Outage.Outage", b =>
                {
                    b.Navigation("AdditionalEquipment");

                    b.Navigation("Authorisations");

                    b.Navigation("ChangeRequests");

                    b.Navigation("CommissioningMemos");

                    b.Navigation("GcuAcknowledgements");

                    b.Navigation("NotifyEmails");

                    b.Navigation("OffPoints");

                    b.Navigation("Pics");

                    b.Navigation("SingleLineDiagrams");
                });
#pragma warning restore 612, 618
        }
    }
}
